def generate_system_prompt(thinking_plan: str) -> str:
    """
    Generate a system prompt using the thinking plan.
    
    Args:
        thinking_plan (str): The thinking plan generated by the planner.
        
    Returns:
        str: A formatted system prompt for the final response generation.
    """
    system_prompt = f"""You are a helpful assistant. Use the following thinking plan to guide your response to the user:

{thinking_plan}

Respond directly to the user's query using this plan, but do NOT mention that you're following a plan or include the plan in your response."""
    
    return system_prompt 